In [ ]:
import pandas as pd

In [ ]:
admission_df = pd.read_csv('ADMISSIONS.csv')
admission_df = admission_df[['subject_id', 'admittime', 'dischtime', 'deathtime', 'admission_type', 'ethnicity', 'diagnosis', 'hospital_expire_flag']]

In [ ]:
inputevents_mv_df = pd.read_csv('INPUTEVENTS_MV.csv')
inputevents_mv_df = inputevents_mv_df[['subject_id', 'starttime', 'endtime', 'itemid', 'amount', 'amountuom', 'rate', 'rateuom', 'patientweight']]

In [ ]:
admission_df

,subject_id,admittime,dischtime,deathtime,admission_type,ethnicity,diagnosis,hospital_expire_flag,visit
0,10006,2164-10-23 21:09:00,2164-11-01 17:15:00,NaN,EMERGENCY,BLACK/AFRICAN AMERICAN,SEPSIS,0,1
1,10011,2126-08-14 22:32:00,2126-08-28 18:59:00,2126-08-28 18:59:00,EMERGENCY,UNKNOWN/NOT SPECIFIED,HEPATITIS B,1,1
2,10013,2125-10-04 23:36:00,2125-10-07 15:13:00,2125-10-07 15:13:00,EMERGENCY,UNKNOWN/NOT SPECIFIED,SEPSIS,1,1
3,10017,2149-05-26 17:19:00,2149-06-03 18:42:00,NaN,EMERGENCY,WHITE,HUMERAL FRACTURE,0,1
4,10019,2163-05-14 20:43:00,2163-05-15 12:00:00,2163-05-15 12:00:00,EMERGENCY,WHITE,ALCOHOLIC HEPATITIS,1,1
...,...,...,...,...,...,...,...,...,...
124,44083,2112-05-28 15:45:00,2112-06-07 16:50:00,NaN,EMERGENCY,WHITE,PERICARDIAL EFFUSION,0,3
125,44154,2178-05-14 20:29:00,2178-05-15 09:45:00,2178-05-15 09:45:00,EMERGENCY,WHITE,ALTERED MENTAL STATUS,1,1
126,44212,2123-11-24 14:14:00,2123-12-30 14:31:00,NaN,EMERGENCY,BLACK/AFRICAN AMERICAN,ACUTE RESPIRATORY DISTRESS SYNDROME;ACUTE RENA...,0,1
127,44222,2180-07-19 06:55:00,2180-07-20 13:00:00,NaN,EMERGENCY,WHITE,BRADYCARDIA,0,1
128,44228,2170-12-15 03:14:00,2170-12-24 18:00:00,NaN,EMERGENCY,WHITE,CHOLANGITIS,0,1

In [ ]:
inputevents_mv_df

,subject_id,starttime,endtime,itemid,amount,amountuom,rate,rateuom,patientweight
0,42367,2147-10-29 16:45:00,2147-10-29 16:46:00,225799,60.000000,ml,NaN,NaN,70.0
1,42367,2147-10-20 13:17:00,2147-10-20 13:18:00,223258,10.000000,units,NaN,NaN,70.0
2,42367,2147-10-29 03:23:00,2147-10-29 03:53:00,226089,99.999999,ml,199.999998,mL/hour,70.0
3,42367,2147-10-22 22:00:00,2147-10-22 22:01:00,225799,40.000000,ml,NaN,NaN,70.0
4,42367,2147-10-16 06:21:00,2147-10-17 06:10:00,225936,1309.899995,ml,54.999300,mL/hour,70.0
...,...,...,...,...,...,...,...,...,...
13219,41976,2202-05-02 13:50:00,2202-05-02 13:51:00,225851,1.000000,dose,NaN,NaN,73.4
13220,41976,2202-05-02 13:50:00,2202-05-02 13:51:00,220949,100.000000,ml,NaN,NaN,73.4
13221,41976,2202-05-02 01:00:00,2202-05-02 01:01:00,225851,1.000000,dose,NaN,NaN,73.4
13222,41976,2202-05-02 01:00:00,2202-05-02 01:01:00,220949,50.000000,ml,NaN,NaN,73.4
13223,41976,2202-05-02 01:00:00,2202-05-02 14:18:00,225823,999.999974,ml,75.187968,mL/hour,73.4

In [ ]:
admission_df['visit'] = admission_df.groupby('subject_id').cumcount() + 1

In [ ]:
admission1_df = admission_df.sort_values(by=['subject_id', 'admittime'])
inputevents_mv1_df = inputevents_mv_df.sort_values(by=['subject_id', 'starttime'])

inputevents_mv1_df['visit'] = 0

for index, row in inputevents_mv1_df.iterrows():
    subject_id = row['subject_id']
    starttime = row['starttime']
    endtime = row['endtime']

    # Find the corresponding admission for the subject
    matching_admission = admission1_df[(admission1_df['subject_id'] == subject_id) & (admission1_df['admittime'] <= starttime) & (admission1_df['dischtime'] >= endtime)]
    if not matching_admission.empty:
        # If a matching admission is found, mark the visit based on its index
        inputevents_mv1_df.at[index, 'visit'] = matching_admission['visit']

In [ ]:
inputevents_mv1_df

,subject_id,starttime,endtime,itemid,amount,amountuom,rate,rateuom,patientweight,visit
5925,40124,2130-02-04 04:35:00,2130-02-05 08:21:00,225152,24999.999332,units,900.360120,units/hour,41.5,1
5926,40124,2130-02-04 04:35:00,2130-02-05 08:21:00,220949,250.000010,ml,9.003602,mL/hour,41.5,1
5930,40124,2130-02-04 04:35:00,2130-02-04 14:46:00,225152,9169.999202,units,900.490920,units/hour,41.5,1
5931,40124,2130-02-04 04:35:00,2130-02-04 14:46:00,220949,91.699998,ml,9.004910,mL/hour,41.5,1
5936,40124,2130-02-04 04:36:00,2130-02-04 10:00:00,222168,538.205958,mg,40.027217,mcg/kg/min,41.5,1
...,...,...,...,...,...,...,...,...,...,...
2128,44228,2170-12-19 11:02:00,2170-12-19 11:03:00,223258,5.000000,units,NaN,NaN,52.3,1
2223,44228,2170-12-19 16:30:00,2170-12-19 18:30:00,227522,99.999997,ml,49.999999,mL/hour,52.3,1
2224,44228,2170-12-19 16:30:00,2170-12-19 18:30:00,225166,20.000000,mEq,NaN,NaN,52.3,1
2245,44228,2170-12-19 17:00:00,2170-12-19 17:01:00,225893,1.000000,dose,NaN,NaN,52.3,1
2246,44228,2170-12-19 17:00:00,2170-12-19 17:01:00,220949,100.000000,ml,NaN,NaN,52.3,1

In [ ]:
inputevents_mv1_df.columns.to_list()

['subject_id',
 'starttime',
 'endtime',
 'itemid',
 'amount',
 'amountuom',
 'rate',
 'rateuom',
 'patientweight',
 'visit']

In [ ]:
inputevents_mv1_df.to_csv('merged_data.csv', index=False)

In [ ]:
visit_2_entries = inputevents_mv1_df[inputevents_mv1_df['visit'] == 2]
visit_2_entries

,subject_id,starttime,endtime,itemid,amount,amountuom,rate,rateuom,patientweight,visit
10435,40124,2130-08-12 09:22:00,2130-08-12 10:36:00,221744,0.030833,mg,25.000001,mcg/hour,47.4,2
10436,40124,2130-08-12 09:22:00,2130-08-12 10:36:00,220949,3.083333,ml,2.500000,mL/hour,47.4,2
10516,40124,2130-08-12 09:22:00,2130-08-12 10:29:00,221668,3.350000,mg,3.000000,mg/hour,47.4,2
10517,40124,2130-08-12 09:22:00,2130-08-12 10:29:00,225158,3.350000,ml,3.000000,mL/hour,47.4,2
10518,40124,2130-08-12 10:29:00,2130-08-12 10:33:00,221668,0.193300,mg,2.899500,mg/hour,47.4,2
...,...,...,...,...,...,...,...,...,...,...
8293,44083,2112-05-24 06:00:00,2112-05-24 07:00:00,227523,49.999999,ml,49.999999,mL/hour,98.6,2
8294,44083,2112-05-24 06:00:00,2112-05-24 07:00:00,222011,2.000000,grams,NaN,NaN,98.6,2
8295,44083,2112-05-24 09:15:00,2112-05-24 09:16:00,226452,100.000000,ml,NaN,NaN,98.6,2
8292,44083,2112-05-24 12:00:00,2112-05-24 12:01:00,226452,100.000000,ml,NaN,NaN,98.6,2
8291,44083,2112-05-24 20:09:00,2112-05-24 20:10:00,226452,120.000000,ml,NaN,NaN,98.6,2

In [ ]:
unique_itemids = inputevents_mv1_df['itemid'].unique()

# Create a list of unique SUBJECT_ID + visit combinations
unique_subject_visits = inputevents_mv1_df['subject_id'].astype(str) + inputevents_mv1_df['visit'].astype(str)
unique_subject_visits = unique_subject_visits.unique()

# Initialize an empty DataFrame with rows and columns
matrix_df = pd.DataFrame(0, index=unique_subject_visits, columns=unique_itemids)

# Iterate through inputevents_mv_df to fill the matrix
for index, row in inputevents_mv1_df.iterrows():
    subject_visit = str(row['subject_id']) + str(row['visit'])
    item_id = row['itemid']
    matrix_df.at[subject_visit, item_id] = 1

In [ ]:
matrix_df

,225152,220949,222168,225943,226361,225158,226453,225909,225799,225879,...,227525,221555,227529,227526,221036,225934,225888,227535,225941,225973
401241,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
401242,0,1,0,1,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
401771,0,1,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
401770,0,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
402041,0,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441541,0,1,1,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
441540,0,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
442121,0,1,1,1,0,1,1,1,1,0,...,1,1,1,1,1,1,1,1,0,0
442221,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
442281,0,1,0,1,1,1,0,0,1,0,...,0,0,0,0,0,0,0,0,1,1

In [ ]:
matrix_df.to_csv('matrix.csv')

In [ ]:
matrix_updated_df = pd.read_csv('matrix_updated.csv')
matrix_updated_df

,subject_visit,225152,220949,222168,225943,226361,225158,226453,225909,225799,...,227525,221555,227529,227526,221036,225934,225888,227535,225941,225973
0,401241,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,401242,0,1,0,1,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,401771,0,1,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,401770,0,0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,402041,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,441541,0,1,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
77,441540,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
78,442121,0,1,1,1,0,1,1,1,1,...,1,1,1,1,1,1,1,1,0,0
79,442221,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
80,442281,0,1,0,1,1,1,0,0,1,...,0,0,0,0,0,0,0,0,1,1

In [ ]:
matrix_updated_df['visit'] = matrix_updated_df['subject_visit'] % 10
matrix_updated_df['subject_id'] = matrix_updated_df['subject_visit'] // 10
matrix_updated_df = matrix_updated_df.drop(columns=['subject_visit'])

In [ ]:
matrix_updated_df

,225152,220949,222168,225943,226361,225158,226453,225909,225799,225879,...,227529,227526,221036,225934,225888,227535,225941,225973,visit,subject_id
0,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,1,40124
1,0,1,0,1,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,2,40124
2,0,1,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,40177
3,0,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,40177
4,0,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,40204
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,0,1,1,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,44154
77,0,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,44154
78,0,1,1,1,0,1,1,1,1,0,...,1,1,1,1,1,1,0,0,1,44212
79,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,44222
80,0,1,0,1,1,1,0,0,1,0,...,0,0,0,0,0,0,1,1,1,44228

In [ ]:
unique_itemid_d = inputevents_mv1_df['itemid'].unique()

# Create a list of unique "subject_id + visit" combinations
unique_subject_visits = inputevents_mv1_df['subject_id'].astype(str) + inputevents_mv1_df['visit'].astype(str)
unique_subject_visits = unique_subject_visits.unique()

# Initialize an empty DataFrame with rows and columns
matrix_df1 = pd.DataFrame(0, index=unique_subject_visits, columns=unique_itemid_d)

# Iterate through inputevents_mv1 to fill the matrix with the sum of the total amount
for index, row in inputevents_mv1_df.iterrows():
    subject_visit = str(row['subject_id']) + str(row['visit'])
    itemid_d = row['itemid']
    amount = row['amount']
    matrix_df1.at[subject_visit, itemid_d] += amount

In [ ]:
matrix_df1

,225152,220949,222168,225943,226361,225158,226453,225909,225799,225879,...,227525,221555,227529,227526,221036,225934,225888,227535,225941,225973
401241,101620.405104,1166.204108,538.205958,53.820599,2000,4434.999992,40,1,30,1,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0
401242,0.000000,1647.153164,0.000000,20.000000,0,5051.304812,0,0,200,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0
401771,0.000000,900.000000,0.000000,0.000000,1500,5326.358592,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0
401770,0.000000,0.000000,0.000000,3.583334,0,314.141384,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0
402041,0.000000,200.000000,0.000000,0.000000,0,562.436809,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441541,0.000000,154.685322,4535.152772,453.515260,2000,2970.074120,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0
441540,0.000000,9.333334,0.000000,0.000000,0,343.833343,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0
442121,0.000000,46696.899016,10664.312890,2506.431283,0,48836.552412,2845,4,5425,0,...,1513.502972,333.589679,193835.906458,21884.074029,833.516585,5632.93474,7,5.0,0.000000,0.0
442221,0.000000,0.000000,0.000000,0.000000,700,0.000000,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0
442281,0.000000,3400.000000,0.000000,40.000000,11000,2502.368954,0,0,900,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,1000.000048,12.5

patient_weight, visit, diagnosis, hospital_expire_flag

In [ ]:
matrix_df1.to_csv('matrix1.csv')

In [ ]:
matrix_updated_df1 = pd.read_csv('matrix1_updated.csv')
matrix_updated_df1

,subject_visit,225152,220949,222168,225943,226361,225158,226453,225909,225799,...,227525,221555,227529,227526,221036,225934,225888,227535,225941,225973
0,401241,101620.405104,1166.204108,538.205958,53.820599,2000,4434.999992,40,1,30,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0
1,401242,0.000000,1647.153164,0.000000,20.000000,0,5051.304812,0,0,200,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0
2,401771,0.000000,900.000000,0.000000,0.000000,1500,5326.358592,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0
3,401770,0.000000,0.000000,0.000000,3.583334,0,314.141384,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0
4,402041,0.000000,200.000000,0.000000,0.000000,0,562.436809,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,441541,0.000000,154.685322,4535.152772,453.515260,2000,2970.074120,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0
77,441540,0.000000,9.333334,0.000000,0.000000,0,343.833343,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0
78,442121,0.000000,46696.899016,10664.312890,2506.431283,0,48836.552412,2845,4,5425,...,1513.502972,333.589679,193835.906458,21884.074029,833.516585,5632.93474,7,5.0,0.000000,0.0
79,442221,0.000000,0.000000,0.000000,0.000000,700,0.000000,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0
80,442281,0.000000,3400.000000,0.000000,40.000000,11000,2502.368954,0,0,900,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,1000.000048,12.5

In [ ]:
matrix_updated_df1['subject_id'] = matrix_updated_df1['subject_visit'] // 10
matrix_updated_df1 = matrix_updated_df1.drop(columns=['subject_visit'])

In [ ]:
matrix_updated_df1

,225152,220949,222168,225943,226361,225158,226453,225909,225799,225879,...,221555,227529,227526,221036,225934,225888,227535,225941,225973,subject_id
0,101620.405104,1166.204108,538.205958,53.820599,2000,4434.999992,40,1,30,1,...,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,40124
1,0.000000,1647.153164,0.000000,20.000000,0,5051.304812,0,0,200,0,...,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,40124
2,0.000000,900.000000,0.000000,0.000000,1500,5326.358592,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,40177
3,0.000000,0.000000,0.000000,3.583334,0,314.141384,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,40177
4,0.000000,200.000000,0.000000,0.000000,0,562.436809,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,40204
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,0.000000,154.685322,4535.152772,453.515260,2000,2970.074120,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,44154
77,0.000000,9.333334,0.000000,0.000000,0,343.833343,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,44154
78,0.000000,46696.899016,10664.312890,2506.431283,0,48836.552412,2845,4,5425,0,...,333.589679,193835.906458,21884.074029,833.516585,5632.93474,7,5.0,0.000000,0.0,44212
79,0.000000,0.000000,0.000000,0.000000,700,0.000000,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,44222
80,0.000000,3400.000000,0.000000,40.000000,11000,2502.368954,0,0,900,0,...,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,1000.000048,12.5,44228

In [ ]:
merged_df = matrix_updated_df.merge(matrix_updated_df1, on='subject_id', how='inner')

In [ ]:
merged_df

,225152_x,220949_x,222168_x,225943_x,226361_x,225158_x,226453_x,225909_x,225799_x,225879_x,...,227525_y,221555_y,227529_y,227526_y,221036_y,225934_y,225888_y,227535_y,225941_y,225973_y
0,1,1,1,1,1,1,1,1,1,1,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0
1,1,1,1,1,1,1,1,1,1,1,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0
2,0,1,0,1,0,1,0,0,1,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0
3,0,1,0,1,0,1,0,0,1,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0
4,0,1,0,0,1,1,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218,0,1,0,0,0,1,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0
219,0,1,0,0,0,1,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0
220,0,1,1,1,0,1,1,1,1,0,...,1513.502972,333.589679,193835.906458,21884.074029,833.516585,5632.93474,7,5.0,0.000000,0.0
221,0,0,0,0,1,0,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0
222,0,1,0,1,1,1,0,0,1,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,1000.000048,12.5

In [ ]:
merged_df = merged_df[['subject_id'] + [col for col in merged_df.columns if col != 'subject_id']]
merged_df

,subject_id,225152_x,220949_x,222168_x,225943_x,226361_x,225158_x,226453_x,225909_x,225799_x,...,227525_y,221555_y,227529_y,227526_y,221036_y,225934_y,225888_y,227535_y,225941_y,225973_y
0,40124,1,1,1,1,1,1,1,1,1,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0
1,40124,1,1,1,1,1,1,1,1,1,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0
2,40124,0,1,0,1,0,1,0,0,1,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0
3,40124,0,1,0,1,0,1,0,0,1,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0
4,40177,0,1,0,0,1,1,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218,44154,0,1,0,0,0,1,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0
219,44154,0,1,0,0,0,1,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0
220,44212,0,1,1,1,0,1,1,1,1,...,1513.502972,333.589679,193835.906458,21884.074029,833.516585,5632.93474,7,5.0,0.000000,0.0
221,44222,0,0,0,0,1,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0
222,44228,0,1,0,1,1,1,0,0,1,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,1000.000048,12.5

In [ ]:


# Assuming you have DataFrames named merged_df and admissions

# Merge the 'admissions' DataFrame with 'merged_df' to get diagnosis for matching subject_id and visit
result = pd.merge(merged_df, admission_df[['subject_id', 'visit', 'diagnosis']], on=['subject_id', 'visit'], how='left')

# Reorder the columns to have 'diagnosis' as the last column
result = result[['subject_id', 'visit'] + [col for col in merged_df.columns if col not in ['subject_id', 'visit']] + ['diagnosis']]
result

,subject_id,visit,225152_x,220949_x,222168_x,225943_x,226361_x,225158_x,226453_x,225909_x,...,221555_y,227529_y,227526_y,221036_y,225934_y,225888_y,227535_y,225941_y,225973_y,diagnosis
0,40124,1,1,1,1,1,1,1,1,1,...,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,SHORTNESS OF BREATH
1,40124,1,1,1,1,1,1,1,1,1,...,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,SHORTNESS OF BREATH
2,40124,2,0,1,0,1,0,1,0,0,...,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,PNEUMONIA
3,40124,2,0,1,0,1,0,1,0,0,...,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,PNEUMONIA
4,40177,1,0,1,0,0,1,1,0,0,...,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,ACUTE CHOLANGITIS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218,44154,0,0,1,0,0,0,1,0,0,...,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,NaN
219,44154,0,0,1,0,0,0,1,0,0,...,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,NaN
220,44212,1,0,1,1,1,0,1,1,1,...,333.589679,193835.906458,21884.074029,833.516585,5632.93474,7,5.0,0.000000,0.0,ACUTE RESPIRATORY DISTRESS SYNDROME;ACUTE RENA...
221,44222,1,0,0,0,0,1,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,BRADYCARDIA
222,44228,1,0,1,0,1,1,1,0,0,...,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,1000.000048,12.5,CHOLANGITIS

In [ ]:
result = result.dropna(subset=['diagnosis'])
result

,subject_id,visit,225152_x,220949_x,222168_x,225943_x,226361_x,225158_x,226453_x,225909_x,...,221555_y,227529_y,227526_y,221036_y,225934_y,225888_y,227535_y,225941_y,225973_y,diagnosis
0,40124,1,1,1,1,1,1,1,1,1,...,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,SHORTNESS OF BREATH
1,40124,1,1,1,1,1,1,1,1,1,...,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,SHORTNESS OF BREATH
2,40124,2,0,1,0,1,0,1,0,0,...,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,PNEUMONIA
3,40124,2,0,1,0,1,0,1,0,0,...,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,PNEUMONIA
4,40177,1,0,1,0,0,1,1,0,0,...,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,ACUTE CHOLANGITIS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,44154,1,0,1,1,1,1,1,0,0,...,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,ALTERED MENTAL STATUS
217,44154,1,0,1,1,1,1,1,0,0,...,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,ALTERED MENTAL STATUS
220,44212,1,0,1,1,1,0,1,1,1,...,333.589679,193835.906458,21884.074029,833.516585,5632.93474,7,5.0,0.000000,0.0,ACUTE RESPIRATORY DISTRESS SYNDROME;ACUTE RENA...
221,44222,1,0,0,0,0,1,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,BRADYCARDIA
222,44228,1,0,1,0,1,1,1,0,0,...,0.000000,0.000000,0.000000,0.000000,0.00000,0,0.0,1000.000048,12.5,CHOLANGITIS

In [ ]:
admissions = admission_df.drop_duplicates(subset=['subject_id', 'visit'])
print(admissions['hospital_expire_flag'].value_counts())
result1 = result.merge(admissions[['subject_id', 'hospital_expire_flag']], on='subject_id', how='left')
# result1 = result1.drop_duplicates(subset=['subject_id', 'visit'])

0    89
1    40
Name: hospital_expire_flag, dtype: int64

In [ ]:
result1

,subject_id,visit,225152_x,220949_x,222168_x,225943_x,226361_x,225158_x,226453_x,225909_x,...,227529_y,227526_y,221036_y,225934_y,225888_y,227535_y,225941_y,225973_y,diagnosis,hospital_expire_flag
0,40124,1,1,1,1,1,1,1,1,1,...,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,SHORTNESS OF BREATH,0
1,40124,1,1,1,1,1,1,1,1,1,...,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,SHORTNESS OF BREATH,0
2,40124,1,1,1,1,1,1,1,1,1,...,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,SHORTNESS OF BREATH,0
3,40124,1,1,1,1,1,1,1,1,1,...,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,SHORTNESS OF BREATH,0
4,40124,2,0,1,0,1,0,1,0,0,...,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,PNEUMONIA,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475,44154,1,0,1,1,1,1,1,0,0,...,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,ALTERED MENTAL STATUS,1
1476,44154,1,0,1,1,1,1,1,0,0,...,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,ALTERED MENTAL STATUS,1
1477,44212,1,0,1,1,1,0,1,1,1,...,193835.906458,21884.074029,833.516585,5632.93474,7,5.0,0.000000,0.0,ACUTE RESPIRATORY DISTRESS SYNDROME;ACUTE RENA...,0
1478,44222,1,0,0,0,0,1,0,0,0,...,0.000000,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,BRADYCARDIA,0
1479,44228,1,0,1,0,1,1,1,0,0,...,0.000000,0.000000,0.000000,0.00000,0,0.0,1000.000048,12.5,CHOLANGITIS,0

In [ ]:
result2['hospital_expire_flag'].value_counts()

0    19090
1       76
Name: hospital_expire_flag, dtype: int64

In [ ]:
inputevents = inputevents_mv1_df.drop_duplicates(subset=['subject_id', 'visit'])
result2 = result1.merge(inputevents[['subject_id', 'patientweight']], on='subject_id', how='left')
# result2 = result2.drop_duplicates(subset=['subject_id', 'visit'])
result2

,subject_id,visit,225152_x,220949_x,222168_x,225943_x,226361_x,225158_x,226453_x,225909_x,...,227526_y,221036_y,225934_y,225888_y,227535_y,225941_y,225973_y,diagnosis,hospital_expire_flag,patientweight
0,40124,1,1,1,1,1,1,1,1,1,...,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,SHORTNESS OF BREATH,0,41.5
1,40124,1,1,1,1,1,1,1,1,1,...,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,SHORTNESS OF BREATH,0,47.4
2,40124,1,1,1,1,1,1,1,1,1,...,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,SHORTNESS OF BREATH,0,41.5
3,40124,1,1,1,1,1,1,1,1,1,...,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,SHORTNESS OF BREATH,0,47.4
4,40124,1,1,1,1,1,1,1,1,1,...,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,SHORTNESS OF BREATH,0,41.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19161,44154,1,0,1,1,1,1,1,0,0,...,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,ALTERED MENTAL STATUS,1,77.4
19162,44154,1,0,1,1,1,1,1,0,0,...,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,ALTERED MENTAL STATUS,1,77.4
19163,44212,1,0,1,1,1,0,1,1,1,...,21884.074029,833.516585,5632.93474,7,5.0,0.000000,0.0,ACUTE RESPIRATORY DISTRESS SYNDROME;ACUTE RENA...,0,87.0
19164,44222,1,0,0,0,0,1,0,0,0,...,0.000000,0.000000,0.00000,0,0.0,0.000000,0.0,BRADYCARDIA,0,106.0
19165,44228,1,0,1,0,1,1,1,0,0,...,0.000000,0.000000,0.00000,0,0.0,1000.000048,12.5,CHOLANGITIS,0,52.3

In [ ]:
result2.to_csv('result_new.csv')

In [ ]:
result_columns = result2.columns
result_columns

Index(['subject_id', 'visit', '225152_x', '220949_x', '222168_x', '225943_x',
       '226361_x', '225158_x', '226453_x', '225909_x',
       ...
       '227526_y', '221036_y', '225934_y', '225888_y', '227535_y', '225941_y',
       '225973_y', 'diagnosis', 'hospital_expire_flag', 'patientweight'],
      dtype='object', length=275)